[package]
name = "rustodon"
version = "0.1.0"
edition = "2024"
rust-version = "1.97.1"
description = "A mostly-in-place Mastodon replacement written in Rust"
publish = false

[dependencies]
aes-gcm = "0.10.3"
base64 = "0.22.1"
chrono = { version = "0.4.41", default-features = false, features = ["clock"] }
clap = { version = "4.5", features = ["derive"] }
flate2 = { version = "1.1", default-features = false, features = ["rust_backend"] }
ipnetwork = "0.20.0"
pbkdf2 = "0.12.2"
rsa = { version = "0.9.10", features = ["pem", "sha2"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12"] }
rustix = { version = "1.1", features = ["fs"] }
saphyr = { version = "=0.0.6", default-features = false }
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
sha1 = "0.10.7"
sha2 = { version = "0.10.9", features = ["oid"] }
sqlx = { version = "0.8.6", default-features = false, features = ["runtime-tokio", "tls-rustls-ring-webpki", "postgres", "chrono", "json", "ipnetwork", "derive"] }
tokio = { version = "1.47", features = ["macros", "net", "rt-multi-thread", "sync"] }
url = "2.5"
webpki-roots = "0.26.11"
zeroize = "1.9"

[dev-dependencies]
axum = "0.8"
reqwest = { version = "0.12", default-features = false }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "warn"
pedantic = "warn"
