[package]
name = "rustodon"
version = "0.1.0"
edition = "2024"
rust-version = "1.97.1"
description = "A mostly-in-place Mastodon replacement written in Rust"
publish = false

[dependencies]
chrono = { version = "0.4.41", default-features = false, features = ["clock"] }
clap = { version = "4.5", features = ["derive"] }
ipnetwork = "0.20.0"
saphyr = { version = "=0.0.6", default-features = false }
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
sqlx = { version = "0.8.6", default-features = false, features = ["runtime-tokio", "postgres", "chrono", "json", "ipnetwork", "derive"] }
tokio = { version = "1.47", features = ["macros", "net", "rt-multi-thread", "sync"] }

[dev-dependencies]
axum = "0.8"
reqwest = { version = "0.12", default-features = false }
sha2 = "0.10"
url = "2.5"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "warn"
pedantic = "warn"
