//! Advertised API route inventory and the required v1 route contract.

use super::*;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ApiRouteSupport {
    Implemented,
    DisabledResponse,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ApiMethod {
    Get,
    Post,
    Delete,
    Patch,
    Put,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ApiAuthentication {
    Public,
    Optional(&'static [&'static str]),
    Required(&'static [&'static str]),
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum PaginationContract {
    None,
    StatusId,
    RelationshipId,
    AssociationId,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(super) enum ApiCachePolicy {
    Public,
    Anonymous,
    Private,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ApiRouteContract {
    pub path: &'static str,
    pub method: ApiMethod,
    pub support: ApiRouteSupport,
    pub authentication: ApiAuthentication,
    pub pagination: PaginationContract,
    pub(super) cache: ApiCachePolicy,
}

macro_rules! route {
    ($path:literal, $support:ident, $authentication:expr, $pagination:ident, $cache:ident) => {
        ApiRouteContract {
            path: $path,
            method: ApiMethod::Get,
            support: ApiRouteSupport::$support,
            authentication: $authentication,
            pagination: PaginationContract::$pagination,
            cache: ApiCachePolicy::$cache,
        }
    };
}

macro_rules! post_route {
    ($path:literal, $support:ident, $authentication:expr, $pagination:ident, $cache:ident) => {
        ApiRouteContract {
            path: $path,
            method: ApiMethod::Post,
            support: ApiRouteSupport::$support,
            authentication: $authentication,
            pagination: PaginationContract::$pagination,
            cache: ApiCachePolicy::$cache,
        }
    };
}

macro_rules! delete_route {
    ($path:literal, $support:ident, $authentication:expr, $pagination:ident, $cache:ident) => {
        ApiRouteContract {
            path: $path,
            method: ApiMethod::Delete,
            support: ApiRouteSupport::$support,
            authentication: $authentication,
            pagination: PaginationContract::$pagination,
            cache: ApiCachePolicy::$cache,
        }
    };
}

macro_rules! patch_route {
    ($path:literal, $support:ident, $authentication:expr, $pagination:ident, $cache:ident) => {
        ApiRouteContract {
            path: $path,
            method: ApiMethod::Patch,
            support: ApiRouteSupport::$support,
            authentication: $authentication,
            pagination: PaginationContract::$pagination,
            cache: ApiCachePolicy::$cache,
        }
    };
}

macro_rules! put_route {
    ($path:literal, $support:ident, $authentication:expr, $pagination:ident, $cache:ident) => {
        ApiRouteContract {
            path: $path,
            method: ApiMethod::Put,
            support: ApiRouteSupport::$support,
            authentication: $authentication,
            pagination: PaginationContract::$pagination,
            cache: ApiCachePolicy::$cache,
        }
    };
}

pub(super) const READ_FAMILIAR_FOLLOWERS: RequiredScopes =
    RequiredScopes::new(&["read", "read:follows"]);

pub const API_ROUTE_INVENTORY: &[ApiRouteContract] = &[
    put_route!(
        "/api/web/settings",
        Implemented,
        ApiAuthentication::Optional(NO_SCOPE.as_slice()),
        None,
        Private
    ),
    patch_route!(
        "/api/web/settings",
        Implemented,
        ApiAuthentication::Optional(NO_SCOPE.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v1/trends/tags",
        DisabledResponse,
        ApiAuthentication::Optional(NO_SCOPE.as_slice()),
        None,
        Anonymous
    ),
    route!(
        "/api/v1/trends/links",
        DisabledResponse,
        ApiAuthentication::Optional(NO_SCOPE.as_slice()),
        None,
        Anonymous
    ),
    route!(
        "/api/v1/trends/statuses",
        DisabledResponse,
        ApiAuthentication::Optional(NO_SCOPE.as_slice()),
        None,
        Anonymous
    ),
    route!(
        "/api/v1/directory",
        DisabledResponse,
        ApiAuthentication::Optional(NO_SCOPE.as_slice()),
        None,
        Anonymous
    ),
    route!(
        "/api/v1/timelines/link",
        DisabledResponse,
        ApiAuthentication::Optional(READ_STATUSES.as_slice()),
        None,
        Anonymous
    ),
    route!(
        "/api/v2/suggestions",
        DisabledResponse,
        ApiAuthentication::Required(READ_ACCOUNTS.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v1/domain_blocks",
        Implemented,
        ApiAuthentication::Required(READ_BLOCKS.as_slice()),
        AssociationId,
        Private
    ),
    route!(
        "/api/v1/instance/domain_blocks",
        Implemented,
        ApiAuthentication::Optional(NO_SCOPE.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v1/accounts/familiar_followers",
        DisabledResponse,
        ApiAuthentication::Required(READ_FAMILIAR_FOLLOWERS.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v1/instance",
        Implemented,
        ApiAuthentication::Public,
        None,
        Public
    ),
    route!(
        "/api/v2/instance",
        Implemented,
        ApiAuthentication::Public,
        None,
        Public
    ),
    route!(
        "/api/v1/instance/extended_description",
        Implemented,
        ApiAuthentication::Public,
        None,
        Public
    ),
    route!(
        "/api/v1/instance/rules",
        Implemented,
        ApiAuthentication::Public,
        None,
        Public
    ),
    route!(
        "/api/v1/instance/translation_languages",
        DisabledResponse,
        ApiAuthentication::Public,
        None,
        Public
    ),
    route!(
        "/api/v1/custom_emojis",
        Implemented,
        ApiAuthentication::Public,
        None,
        Public
    ),
    route!(
        "/api/v1/accounts/lookup",
        Implemented,
        ApiAuthentication::Optional(READ_ACCOUNTS.as_slice()),
        None,
        Anonymous
    ),
    route!(
        "/api/v1/accounts/search",
        Implemented,
        ApiAuthentication::Required(READ_ACCOUNTS.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v1/announcements",
        Implemented,
        ApiAuthentication::Required(NO_SCOPE.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v2/search",
        Implemented,
        ApiAuthentication::Optional(READ_SEARCH.as_slice()),
        None,
        Anonymous
    ),
    post_route!(
        "/api/v1/apps",
        Implemented,
        ApiAuthentication::Public,
        None,
        Private
    ),
    route!(
        "/api/v1/apps/verify_credentials",
        Implemented,
        ApiAuthentication::Required(NO_SCOPE.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v1/markers",
        Implemented,
        ApiAuthentication::Required(READ_STATUSES.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/markers",
        Implemented,
        ApiAuthentication::Required(WRITE_STATUSES.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/statuses",
        Implemented,
        ApiAuthentication::Required(WRITE_STATUSES.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v1/polls/{id}",
        Implemented,
        ApiAuthentication::Optional(READ_STATUSES.as_slice()),
        None,
        Anonymous
    ),
    post_route!(
        "/api/v1/polls/{id}/votes",
        Implemented,
        ApiAuthentication::Required(WRITE_STATUSES.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/reports",
        Implemented,
        ApiAuthentication::Required(WRITE_REPORTS.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/media",
        Implemented,
        ApiAuthentication::Required(WRITE_MEDIA.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v1/media/{id}",
        Implemented,
        ApiAuthentication::Required(WRITE_MEDIA.as_slice()),
        None,
        Private
    ),
    patch_route!(
        "/api/v1/media/{id}",
        Implemented,
        ApiAuthentication::Required(WRITE_MEDIA.as_slice()),
        None,
        Private
    ),
    put_route!(
        "/api/v1/media/{id}",
        Implemented,
        ApiAuthentication::Required(WRITE_MEDIA.as_slice()),
        None,
        Private
    ),
    delete_route!(
        "/api/v1/media/{id}",
        Implemented,
        ApiAuthentication::Required(WRITE_MEDIA.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v2/media",
        Implemented,
        ApiAuthentication::Required(WRITE_MEDIA.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v1/conversations",
        Implemented,
        ApiAuthentication::Required(READ_STATUSES.as_slice()),
        StatusId,
        Private
    ),
    post_route!(
        "/api/v1/conversations/{id}/read",
        Implemented,
        ApiAuthentication::Required(WRITE_CONVERSATIONS.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/conversations/{id}/unread",
        Implemented,
        ApiAuthentication::Required(WRITE_CONVERSATIONS.as_slice()),
        None,
        Private
    ),
    delete_route!(
        "/api/v1/conversations/{id}",
        Implemented,
        ApiAuthentication::Required(WRITE_CONVERSATIONS.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v1/notifications",
        Implemented,
        ApiAuthentication::Required(READ_NOTIFICATIONS.as_slice()),
        AssociationId,
        Private
    ),
    route!(
        "/api/v2/notifications",
        Implemented,
        ApiAuthentication::Required(READ_NOTIFICATIONS.as_slice()),
        AssociationId,
        Private
    ),
    post_route!(
        "/api/v1/notifications/clear",
        Implemented,
        ApiAuthentication::Required(WRITE_NOTIFICATIONS.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/notifications/{id}/dismiss",
        Implemented,
        ApiAuthentication::Required(WRITE_NOTIFICATIONS.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v2/notifications/clear",
        Implemented,
        ApiAuthentication::Required(WRITE_NOTIFICATIONS.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v2/notifications/{id}/dismiss",
        Implemented,
        ApiAuthentication::Required(WRITE_NOTIFICATIONS.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/notifications/requests/{id}/accept",
        Implemented,
        ApiAuthentication::Required(WRITE_NOTIFICATIONS.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/notifications/requests/{id}/dismiss",
        Implemented,
        ApiAuthentication::Required(WRITE_NOTIFICATIONS.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/notifications/requests/accept",
        Implemented,
        ApiAuthentication::Required(WRITE_NOTIFICATIONS.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/notifications/requests/dismiss",
        Implemented,
        ApiAuthentication::Required(WRITE_NOTIFICATIONS.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v1/notifications/unread_count",
        Implemented,
        ApiAuthentication::Required(READ_NOTIFICATIONS.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v1/notifications/{id}",
        Implemented,
        ApiAuthentication::Required(READ_NOTIFICATIONS.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v1/notifications/requests",
        Implemented,
        ApiAuthentication::Required(READ_NOTIFICATIONS.as_slice()),
        AssociationId,
        Private
    ),
    route!(
        "/api/v1/notifications/requests/merged",
        Implemented,
        ApiAuthentication::Required(READ_NOTIFICATIONS.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v1/notifications/requests/{id}",
        Implemented,
        ApiAuthentication::Required(READ_NOTIFICATIONS.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v1/notifications/policy",
        Implemented,
        ApiAuthentication::Required(READ_NOTIFICATIONS.as_slice()),
        None,
        Private
    ),
    put_route!(
        "/api/v1/notifications/policy",
        Implemented,
        ApiAuthentication::Required(WRITE_NOTIFICATIONS.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v2/notifications/unread_count",
        Implemented,
        ApiAuthentication::Required(READ_NOTIFICATIONS.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v2/notifications/{id}",
        Implemented,
        ApiAuthentication::Required(READ_NOTIFICATIONS.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v2/notifications/policy",
        Implemented,
        ApiAuthentication::Required(READ_NOTIFICATIONS.as_slice()),
        None,
        Private
    ),
    put_route!(
        "/api/v2/notifications/policy",
        Implemented,
        ApiAuthentication::Required(WRITE_NOTIFICATIONS.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v2/filters",
        Implemented,
        ApiAuthentication::Required(READ_FILTERS.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v1/lists",
        Implemented,
        ApiAuthentication::Required(READ_LISTS.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v1/lists/{id}",
        Implemented,
        ApiAuthentication::Required(READ_LISTS.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v1/lists/{id}/accounts",
        Implemented,
        ApiAuthentication::Required(READ_LISTS.as_slice()),
        AssociationId,
        Private
    ),
    route!(
        "/api/v1/accounts/{id}/lists",
        Implemented,
        ApiAuthentication::Required(READ_LISTS.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v1/accounts/{id}/collections",
        Implemented,
        ApiAuthentication::Optional(READ_COLLECTIONS.as_slice()),
        AssociationId,
        Anonymous
    ),
    route!(
        "/api/v1/accounts/{id}/in_collections",
        Implemented,
        ApiAuthentication::Optional(READ_COLLECTIONS.as_slice()),
        AssociationId,
        Anonymous
    ),
    route!(
        "/api/v1/tags/{tag}",
        Implemented,
        ApiAuthentication::Optional(NO_SCOPE.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/featured_tags",
        Implemented,
        ApiAuthentication::Required(WRITE_ACCOUNTS.as_slice()),
        None,
        Private
    ),
    delete_route!(
        "/api/v1/featured_tags/{id}",
        Implemented,
        ApiAuthentication::Required(WRITE_ACCOUNTS.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/tags/{tag}/follow",
        Implemented,
        ApiAuthentication::Required(WRITE_FOLLOWS.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/tags/{tag}/unfollow",
        Implemented,
        ApiAuthentication::Required(WRITE_FOLLOWS.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/tags/{tag}/feature",
        Implemented,
        ApiAuthentication::Required(WRITE_ACCOUNTS.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/tags/{tag}/unfeature",
        Implemented,
        ApiAuthentication::Required(WRITE_ACCOUNTS.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v1/featured_tags",
        Implemented,
        ApiAuthentication::Required(READ_ACCOUNTS.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v1/followed_tags",
        Implemented,
        ApiAuthentication::Required(READ_FOLLOWS.as_slice()),
        AssociationId,
        Private
    ),
    route!(
        "/api/v1/follow_requests",
        Implemented,
        ApiAuthentication::Required(READ_FOLLOWS.as_slice()),
        RelationshipId,
        Private
    ),
    post_route!(
        "/api/v1/follow_requests/{id}/authorize",
        Implemented,
        ApiAuthentication::Required(WRITE_FOLLOWS.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/follow_requests/{id}/reject",
        Implemented,
        ApiAuthentication::Required(WRITE_FOLLOWS.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v1/preferences",
        Implemented,
        ApiAuthentication::Required(READ_ACCOUNTS.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v1/featured_tags/suggestions",
        Implemented,
        ApiAuthentication::Required(READ_ACCOUNTS.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v1/accounts/{id}/featured_tags",
        Implemented,
        ApiAuthentication::Public,
        None,
        Private
    ),
    route!(
        "/api/v1/accounts/relationships",
        Implemented,
        ApiAuthentication::Required(READ_FOLLOWS.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v1/profile",
        Implemented,
        ApiAuthentication::Required(VERIFY_CREDENTIALS.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v1/accounts/verify_credentials",
        Implemented,
        ApiAuthentication::Required(VERIFY_CREDENTIALS.as_slice()),
        None,
        Private
    ),
    patch_route!(
        "/api/v1/accounts/update_credentials",
        Implemented,
        ApiAuthentication::Required(WRITE_ACCOUNTS.as_slice()),
        None,
        Private
    ),
    delete_route!(
        "/api/v1/profile/avatar",
        Implemented,
        ApiAuthentication::Required(WRITE_ACCOUNTS.as_slice()),
        None,
        Private
    ),
    delete_route!(
        "/api/v1/profile/header",
        Implemented,
        ApiAuthentication::Required(WRITE_ACCOUNTS.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v1/accounts",
        Implemented,
        ApiAuthentication::Optional(READ_ACCOUNTS.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v1/accounts/{id}",
        Implemented,
        ApiAuthentication::Optional(READ_ACCOUNTS.as_slice()),
        None,
        Anonymous
    ),
    route!(
        "/api/v1/collections/{id}",
        Implemented,
        ApiAuthentication::Optional(READ_COLLECTIONS.as_slice()),
        None,
        Anonymous
    ),
    route!(
        "/api/v1/accounts/{id}/statuses",
        Implemented,
        ApiAuthentication::Optional(READ_STATUSES.as_slice()),
        StatusId,
        Anonymous
    ),
    route!(
        "/api/v1/accounts/{id}/followers",
        Implemented,
        ApiAuthentication::Optional(READ_ACCOUNTS.as_slice()),
        RelationshipId,
        Anonymous
    ),
    route!(
        "/api/v1/accounts/{id}/following",
        Implemented,
        ApiAuthentication::Optional(READ_ACCOUNTS.as_slice()),
        RelationshipId,
        Anonymous
    ),
    route!(
        "/api/v1/statuses/{id}",
        Implemented,
        ApiAuthentication::Optional(READ_STATUSES.as_slice()),
        None,
        Anonymous
    ),
    patch_route!(
        "/api/v1/statuses/{id}",
        Implemented,
        ApiAuthentication::Required(WRITE_STATUSES.as_slice()),
        None,
        Private
    ),
    put_route!(
        "/api/v1/statuses/{id}",
        Implemented,
        ApiAuthentication::Required(WRITE_STATUSES.as_slice()),
        None,
        Private
    ),
    delete_route!(
        "/api/v1/statuses/{id}",
        Implemented,
        ApiAuthentication::Required(WRITE_STATUSES.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/statuses/{id}/bookmark",
        Implemented,
        ApiAuthentication::Required(WRITE_BOOKMARKS.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/statuses/{id}/unbookmark",
        Implemented,
        ApiAuthentication::Required(WRITE_BOOKMARKS.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/statuses/{id}/favourite",
        Implemented,
        ApiAuthentication::Required(WRITE_FAVOURITES.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/statuses/{id}/unfavourite",
        Implemented,
        ApiAuthentication::Required(WRITE_FAVOURITES.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/statuses/{id}/reblog",
        Implemented,
        ApiAuthentication::Required(WRITE_STATUSES.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/statuses/{id}/unreblog",
        Implemented,
        ApiAuthentication::Required(WRITE_STATUSES.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/statuses/{id}/mute",
        Implemented,
        ApiAuthentication::Required(WRITE_MUTES.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/statuses/{id}/unmute",
        Implemented,
        ApiAuthentication::Required(WRITE_MUTES.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/statuses/{id}/pin",
        Implemented,
        ApiAuthentication::Required(WRITE_ACCOUNTS.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/statuses/{id}/unpin",
        Implemented,
        ApiAuthentication::Required(WRITE_ACCOUNTS.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/accounts/{id}/follow",
        Implemented,
        ApiAuthentication::Required(WRITE_FOLLOWS.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/accounts/{id}/unfollow",
        Implemented,
        ApiAuthentication::Required(WRITE_FOLLOWS.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/accounts/{id}/remove_from_followers",
        Implemented,
        ApiAuthentication::Required(WRITE_FOLLOWS.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/accounts/{id}/block",
        Implemented,
        ApiAuthentication::Required(WRITE_BLOCKS.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/accounts/{id}/unblock",
        Implemented,
        ApiAuthentication::Required(WRITE_BLOCKS.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/accounts/{id}/mute",
        Implemented,
        ApiAuthentication::Required(WRITE_MUTES.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/accounts/{id}/unmute",
        Implemented,
        ApiAuthentication::Required(WRITE_MUTES.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v1/statuses/{id}/source",
        Implemented,
        ApiAuthentication::Required(READ_STATUSES.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v1/statuses/{id}/history",
        Implemented,
        ApiAuthentication::Optional(READ_STATUSES.as_slice()),
        None,
        Anonymous
    ),
    route!(
        "/api/v1/statuses/{id}/quotes",
        Implemented,
        ApiAuthentication::Required(READ_STATUSES.as_slice()),
        AssociationId,
        Private
    ),
    put_route!(
        "/api/v1/statuses/{id}/interaction_policy",
        Implemented,
        ApiAuthentication::Required(WRITE_STATUSES.as_slice()),
        None,
        Private
    ),
    post_route!(
        "/api/v1/statuses/{quoted_status_id}/quotes/{id}/revoke",
        Implemented,
        ApiAuthentication::Required(WRITE_STATUSES.as_slice()),
        None,
        Private
    ),
    route!(
        "/api/v1/statuses/{id}/favourited_by",
        Implemented,
        ApiAuthentication::Optional(READ_ACCOUNTS.as_slice()),
        AssociationId,
        Anonymous
    ),
    route!(
        "/api/v1/statuses/{id}/reblogged_by",
        Implemented,
        ApiAuthentication::Optional(READ_ACCOUNTS.as_slice()),
        StatusId,
        Anonymous
    ),
    route!(
        "/api/v1/statuses/{id}/context",
        Implemented,
        ApiAuthentication::Optional(READ_STATUSES.as_slice()),
        None,
        Anonymous
    ),
    route!(
        "/api/v1/timelines/public",
        Implemented,
        ApiAuthentication::Optional(READ_STATUSES.as_slice()),
        StatusId,
        Anonymous
    ),
    route!(
        "/api/v1/timelines/tag/{hashtag}",
        Implemented,
        ApiAuthentication::Optional(READ_STATUSES.as_slice()),
        StatusId,
        Anonymous
    ),
    route!(
        "/api/v1/timelines/home",
        Implemented,
        ApiAuthentication::Required(READ_STATUSES.as_slice()),
        StatusId,
        Private
    ),
    route!(
        "/api/v1/timelines/list/{id}",
        Implemented,
        ApiAuthentication::Required(READ_LISTS.as_slice()),
        StatusId,
        Private
    ),
    route!(
        "/api/v1/favourites",
        Implemented,
        ApiAuthentication::Required(READ_FAVOURITES.as_slice()),
        AssociationId,
        Private
    ),
    route!(
        "/api/v1/bookmarks",
        Implemented,
        ApiAuthentication::Required(READ_BOOKMARKS.as_slice()),
        AssociationId,
        Private
    ),
    route!(
        "/api/v1/blocks",
        Implemented,
        ApiAuthentication::Required(READ_BLOCKS.as_slice()),
        RelationshipId,
        Private
    ),
    route!(
        "/api/v1/mutes",
        Implemented,
        ApiAuthentication::Required(READ_MUTES.as_slice()),
        RelationshipId,
        Private
    ),
];

/// The REST routes required by `docs/v1-scope.md` for ordinary v1 clients.
///
/// This is deliberately separate from `API_ROUTE_INVENTORY`: the inventory also
/// contains harmless read-only compatibility routes used by the web client.
pub const V1_REQUIRED_API_ROUTES: &[(&str, ApiMethod, ApiRouteSupport)] = &[
    (
        "/api/v1/instance",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v2/instance",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/instance/extended_description",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/instance/rules",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/instance/translation_languages",
        ApiMethod::Get,
        ApiRouteSupport::DisabledResponse,
    ),
    (
        "/api/v1/accounts/{id}",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/accounts/verify_credentials",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/accounts/update_credentials",
        ApiMethod::Patch,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/accounts/lookup",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/accounts/search",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/announcements",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v2/search",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/accounts/relationships",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/accounts/{id}/statuses",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/accounts/{id}/followers",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/accounts/{id}/following",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/statuses",
        ApiMethod::Post,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/polls/{id}",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/polls/{id}/votes",
        ApiMethod::Post,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/reports",
        ApiMethod::Post,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/statuses/{id}",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/statuses/{id}",
        ApiMethod::Patch,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/statuses/{id}",
        ApiMethod::Put,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/statuses/{id}",
        ApiMethod::Delete,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/statuses/{id}/source",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/statuses/{id}/history",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/statuses/{id}/quotes",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/statuses/{id}/interaction_policy",
        ApiMethod::Put,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/statuses/{quoted_status_id}/quotes/{id}/revoke",
        ApiMethod::Post,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/statuses/{id}/context",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/statuses/{id}/bookmark",
        ApiMethod::Post,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/statuses/{id}/unbookmark",
        ApiMethod::Post,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/statuses/{id}/favourite",
        ApiMethod::Post,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/statuses/{id}/unfavourite",
        ApiMethod::Post,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/statuses/{id}/reblog",
        ApiMethod::Post,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/statuses/{id}/unreblog",
        ApiMethod::Post,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/statuses/{id}/favourited_by",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/statuses/{id}/reblogged_by",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/timelines/home",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/timelines/public",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/timelines/tag/{hashtag}",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/timelines/list/{id}",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/favourites",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/bookmarks",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/blocks",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/mutes",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/follow_requests",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/follow_requests/{id}/authorize",
        ApiMethod::Post,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/follow_requests/{id}/reject",
        ApiMethod::Post,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/accounts/{id}/follow",
        ApiMethod::Post,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/accounts/{id}/unfollow",
        ApiMethod::Post,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/accounts/{id}/remove_from_followers",
        ApiMethod::Post,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/accounts/{id}/block",
        ApiMethod::Post,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/accounts/{id}/unblock",
        ApiMethod::Post,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/accounts/{id}/mute",
        ApiMethod::Post,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/accounts/{id}/unmute",
        ApiMethod::Post,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/conversations",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/conversations/{id}/read",
        ApiMethod::Post,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/conversations/{id}/unread",
        ApiMethod::Post,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/conversations/{id}",
        ApiMethod::Delete,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/notifications",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v2/notifications",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/notifications/unread_count",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v2/notifications/unread_count",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/notifications/{id}",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v2/notifications/{id}",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/notifications/clear",
        ApiMethod::Post,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v2/notifications/clear",
        ApiMethod::Post,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/notifications/{id}/dismiss",
        ApiMethod::Post,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v2/notifications/{id}/dismiss",
        ApiMethod::Post,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v2/filters",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/preferences",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/apps",
        ApiMethod::Post,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/apps/verify_credentials",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/markers",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/markers",
        ApiMethod::Post,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/media",
        ApiMethod::Post,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/media/{id}",
        ApiMethod::Get,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/media/{id}",
        ApiMethod::Patch,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/media/{id}",
        ApiMethod::Put,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v1/media/{id}",
        ApiMethod::Delete,
        ApiRouteSupport::Implemented,
    ),
    (
        "/api/v2/media",
        ApiMethod::Post,
        ApiRouteSupport::Implemented,
    ),
];
